### PR TITLE
added notebook for forecasting different smart metrics

### PR DESCRIPTION
**Pull request by SankBad**
This PR address #14 , Repeat Forecasting Pipeline for Other Metrics, particularly, SMART metrics: 187, 188, 197, and 198.

### CODE REVIEW

**Comment by SankBad** [comment]
Updated the changes.

**Comment by SankBad** [comment]
Thanks for the feedback. 
I am making the changes.

**Review by MichaelClifford — APPROVED** [review]

**Review by chauhankaranraj — APPROVED** [review]
Thanks for the updates @SankBad, lgtm :rocket:

**Comment by SankBad** [comment]
@chauhankaranraj , Thanks!
I just squashed the commits.

**Review by chauhankaranraj — APPROVED** [review]

**Pull request merged**
