### PR TITLE
Fix pre-commit errors in result and image files

### LINKED ISSUE #25: Fix linting and formatting errors
As a data scientist, I want to ensure all the code in this repo is well formatted and follows best software quality practices. Since this repo was created way before we had [aicoe-aiops/project-template](https://github.com/aicoe-aiops/project-template) set up, many of the notebooks and scripts have gotten merged into this repo without being properly linted or formatted. This needs to be fixed.

**Acceptance Criterion**
- [x] update notebooks and scripts so that all pre-commit tests are passing

### PR DESCRIPTION
**Pull request by chauhankaranraj**
## Related Issues and Dependencies

Addresses #25 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Fixes the failing pre-commit checks for result mlruns files and saved html images in this repo. Although there are a lot of files being modified in this PR, most of it is just formatting changes such as adding EOL and no "real" changes.

This PR, together with #30, should close #25

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@chauhankaranraj do you want to rebase on the previous merge #30; then we can get the green light on the pre-commit check before merging this one?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj do you want to rebase on the previous merge #30; then we can get the green light on the pre-commit check before merging this one?

Good idea, just pushed :)

**Comment by MichaelClifford** [comment]
:partying_face: 
/approve

**Pull request merged**
