### PR TITLE
rearrange file structure

### PR DESCRIPTION
**Pull request by isabelizimm**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements

Moves notebooks using the Back Blaze dataset into directory `data_sources/backblaze` to better organize files with new datasets (specifically the Telemetry dataset) being analyzed.

### CODE REVIEW

**Review by chauhankaranraj — CHANGES_REQUESTED** [review]
Could you please also update in the notebooks the paths where models/figures are being saved? I.e. `../reports` --> `../../../reports` and `../models` --> `../../../models`

**Comment by 4n4nd** [comment]
@isabelizimm [this](https://github.com/aicoe-aiops/ceph_drive_failure/pull/39) should let you retest stuff

**Comment by isabelizimm** [comment]
> @isabelizimm [this](https://github.com/aicoe-aiops/ceph_drive_failure/pull/39) should let you retest stuff

Got it, thanks for making that update!

**Review by chauhankaranraj — APPROVED** [review]
looks good, thanks!
/approve

**Pull request merged**
